name: Production Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Production Build
    runs-on: ubuntu-latest

    # Set the node version used for the action
    strategy:      
      matrix:        
       node-version: [20.x]

    steps:
      # Setup node
      - name: Use Node.JS ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      # Access code from Git
      - name: Git Checkout
        uses: actions/checkout@v4.1.5

      # Install packages
      - name: Install Packages
        run: npm install

      # Build for production
      - name: Production Build
        run: |
          unset CI
          npm run build

      # Deploy to s3 bucket
      - name: Deploy to AWS S3 Bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete # Check if bucket is publicly readable and delete previous content
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "build"
          
